services:
  - type: web
    name: dashboard-petir-dramaga
    env: python
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 120 --preload
    envVars:
      - key: OPENWEATHER_API_KEY
        value: isi_api_key_openweathermap_disini
      - key: TELEGRAM_BOT_TOKEN
        value: isi_token_bot_telegram_disini
      - key: TELEGRAM_CHAT_ID
        value: isi_chat_id_disini
      - key: TZ
        value: Asia/Jakarta
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "10000"
